AllCops:
  Exclude:
    - 'okuribito.gemspec'
    - 'spec/spec_helper.rb'
    - 'spec/support/**/*'

Documentation:
  Enabled: false

LineLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - double_quotes
