TestTarget:
  - ".deprecated_self_method"
  - "#deprecated_method"
  - "#deprecated_method?"
  - "#deprecated_method!"
  - "#deprecated_method_with_args"
TestModule::TestTarget:
  - "#deprecated_method"
TestModule::NestedTestModule::TestTarget:
  - "#deprecated_method"
