TestTarget:
  - ".deprecated_self_method"
  - "#deprecated_method"
  - "#deprecated_method?"
  - "#deprecated_method!"
TestModule::TestTarget:
  - "#deprecated_method"
TestModule::NestedTestModule::TestTarget:
  - "#deprecated_method"
